/**
 * Copyright Jeffrey Dungen 2017
 * https://github.com/jeffyactive/
 */

const REEL_BIND_OPTIONS = { protocol: 'serial', path: '/dev/serial0' };
const LEFT_REELCEIVER_ID = '001bc50940810000';
const RIGHT_REELCEIVER_ID = '001bc50940810000';
const HUE_IP = '10.0.50.60';
const HUE_USERNAME = '';
const HUE_SEARCH_MILLISECONDS = 8000;
const HEART_BASE_MILLISECONDS = 1920;
const STATS_PERIOD_MILLISECONDS = 3840;
const STATS_SAMPLES = 12;
const MAX_RSSI = 193;
const MIN_RSSI = 160;


module.exports.REEL_BIND_OPTIONS = REEL_BIND_OPTIONS;
module.exports.LEFT_REELCEIVER_ID = LEFT_REELCEIVER_ID;
module.exports.RIGHT_REELCEIVER_ID = RIGHT_REELCEIVER_ID;
module.exports.HUE_IP = HUE_IP;
module.exports.HUE_USERNAME = HUE_USERNAME;
module.exports.HUE_SEARCH_MILLISECONDS = HUE_SEARCH_MILLISECONDS;
module.exports.HEART_BASE_MILLISECONDS = HEART_BASE_MILLISECONDS;
module.exports.STATS_PERIOD_MILLISECONDS = STATS_PERIOD_MILLISECONDS;
module.exports.STATS_SAMPLES = STATS_SAMPLES;
module.exports.MAX_RSSI = MAX_RSSI;
module.exports.MIN_RSSI = MIN_RSSI;
